const quotes = [
    "La perseverancia es el camino hacia el éxito. - Charlie Chaplin",
    "La vida es 10% lo que nos sucede y 90% cómo reaccionamos a ello. - Charles R. Swindoll",
    "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
    "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez con más inteligencia. - Henry Ford",
    "La única forma de hacer un gran trabajo es amar lo que haces. - Steve Jobs",
    "La creatividad es inteligencia divirtiéndose. - Albert Einstein",
    "La disciplina es el puente entre las metas y los logros. - Jim Rohn",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "No te detengas cuando estés cansado, detente cuando hayas terminado. - Marilyn Monroe",
    "El optimismo es la fe que lleva al éxito. - Helen Keller",
    "El único límite para nuestros logros de mañana son nuestras dudas de hoy. - Franklin D. Roosevelt",
    "El éxito es la habilidad de pasar de un fracaso a otro sin perder el entusiasmo. - Winston Churchill",
    "El fracaso es el condimento que le da sabor al éxito. - Truman Capote",
    "El que persevera alcanza. - Proverbio español",
    "La mejor forma de predecir el futuro es crearlo. - Peter Drucker",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer. - John Wooden",
    "La mente es todo. Lo que piensas, lo conviertes. - Buda",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir para siempre. - Mahatma Gandhi",
    "La motivación nos lleva a empezar y el hábito nos hace continuar. - Zig Ziglar",
    "El que no arriesga, no gana. - Proverbio español",
    "El conocimiento es poder. - Francis Bacon",
    "El coraje no siempre ruge. A veces el coraje es la voz callada al final del día diciendo: 'Lo intentaré de nuevo mañana'. - Mary Anne Radmacher",
    "Los grandes logros se obtienen cuando se tiene una gran perseverancia. - Epicteto",
    "La vida es demasiado corta para ser pequeña. - Benjamin Disraeli",
    "No sueñes tu vida, vive tus sueños. - Les Brown",
    "El éxito no se mide en el dinero, se mide en la diferencia que hacemos en la vida de las personas. - Michelle Obama",
    "Cree que puedes y ya estás a mitad de camino. - Theodore Roosevelt",
    "No dejes que los errores de ayer roben la energía de hoy. - Proverbio indio",
    "La única forma de hacer un buen trabajo es amar lo que haces. - Steve Jobs",
    "No hay secretos para el éxito. Es el resultado de la preparación, el trabajo duro y aprender de los fracasos. - Colin Powell",
    "La clave del éxito es empezar antes de estar listo. - Marie Forleo",
    "El único sitio donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "No puedes cambiar tu destino, pero puedes desafiarlo. - Confucio",
    "Si persistes, obtendrás. Si insistes, alcanzarás. - Hipólito Taine",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. - Henry Ford",
    "La oportunidad no llama dos veces. - Séneca",
    "El futuro pertenece a aquellos que creen en la belleza de sus sueños. - Eleanor Roosevelt",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. - Albert Schweitzer",
    "El cambio es el resultado de todo aprendizaje verdadero. - Leo Buscaglia",
    "La actitud es una pequeña cosa que marca una gran diferencia. - Winston Churchill",
    "No hay sustituto para el trabajo duro. - Thomas A. Edison",
    "El único lugar donde tus sueños se vuelven imposibles es en tu propia mente. - Robert H. Schuller",
    "El único lugar donde el éxito precede al trabajo es en el diccionario. - Vidal Sassoon",
    "La mejor venganza es el éxito. - Frank Sinatra",
    "Nunca es demasiado tarde para ser quien podrías haber sido. - George Eliot",
    "No importa lo despacio que vayas, siempre y cuando no te detengas. - Confucio",
    "No puedes cambiar la dirección del viento, pero puedes ajustar las velas para llegar a tu destino. - Proverbio chino",
    "El que quiera prosperar en este mundo debe saber cómo aprovechar cada oportunidad. - Benjamin Disraeli",
    "El éxito no consiste en lo que tienes, sino en quién eres. - Bo Bennett",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer. - John Wooden",
    "La paciencia es la madre de todas las virtudes. - Proverbio francés",
    "La mente es como un paracaídas, solo funciona si está abierta. - Frank Zappa",
    "El futuro pertenece a quienes creen en la belleza de sus sueños. - Eleanor Roosevelt",
    "El único límite a nuestra realización de mañana son nuestras dudas de hoy. - Franklin D. Roosevelt",
    "La disciplina es el puente entre los objetivos y el logro. - Jim Rohn",
    "Nunca dejes que el miedo se interponga en el camino de tus sueños. - Les Brown",
    "El éxito es un viaje, no un destino. - Ben Sweetland",
    "La motivación nos lleva a empezar y el hábito nos hace continuar. - Zig Ziglar",
    "El verdadero liderazgo consiste en hacer las cosas correctas. - Peter Drucker",
    "La clave del éxito es el entusiasmo. - Walter Chrysler",
    "El fracaso es solo la oportunidad de empezar de nuevo, esta vez con más inteligencia. - Henry Ford",
    "La creatividad es la inteligencia divirtiéndose. - Albert Einstein",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "La determinación es el ingrediente clave para el éxito. - Zig Ziglar",
    "Cree en ti mismo y todo será posible. - Kobe Bryant",
    "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. - Albert Schweitzer",
    "Los obstáculos no pueden detenerte. Los problemas no pueden detenerte. Lo más importante es que no te detengas. - Mario Andretti",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. - Henry Ford",
    "El futuro pertenece a quienes creen en la belleza de sus sueños. - Eleanor Roosevelt",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "El conocimiento es poder. - Francis Bacon",
    "La paciencia es el mejor remedio para cada problema. - Tito Livio",
    "El éxito no se mide en el dinero, se mide en la diferencia que hacemos en la vida de las personas. - Michelle Obama",
    "La única forma de hacer un buen trabajo es amar lo que haces. - Steve Jobs",
    "El éxito es la habilidad de pasar de un fracaso a otro sin perder el entusiasmo. - Winston Churchill",
    "El único límite para nuestros logros de mañana son nuestras dudas de hoy. - Franklin D. Roosevelt",
    "No puedes cruzar el mar simplemente mirando el agua. - Rabindranath Tagore",
    "La vida es demasiado corta para ser pequeña. - Benjamin Disraeli",
    "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez con más inteligencia. - Henry Ford",
    "La perseverancia es el camino hacia el éxito. - Charlie Chaplin",
    "El único sitio donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "El conocimiento es la clave del éxito. - Francois Rabelais",
    "El éxito no viene de lo que haces ocasionalmente, sino de lo que haces consistentemente. - Tony Robbins",
    "No te quedes mirando el reloj, haz lo que haga que el tiempo pase. - Earl Nightingale",
    "El éxito consiste en ir de fracaso en fracaso sin perder entusiasmo. - Winston Churchill",
    "Los ganadores nunca se rinden y los que se rinden nunca ganan. - Vince Lombardi",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer. - John Wooden",
    "Los grandes logros siempre nacen de la determinación. - Nelson Mandela",
    "El optimismo es la fe que lleva al éxito. - Helen Keller",
    "Si quieres lograr grandes cosas, debes dejar de hacer pequeñas cosas. - John D. Rockefeller",
    "La diferencia entre una persona exitosa y los demás no es la falta de fuerza o conocimiento, sino la falta de voluntad. - Vince Lombardi",
    "El fracaso es la oportunidad de comenzar de nuevo, esta vez con más experiencia. - Henry Ford",
    "El único límite para nuestros logros de mañana son nuestras dudas de hoy. - Franklin D. Roosevelt",
    "La perseverancia es la clave del éxito. - Bill Gates",
    "El optimismo es la fe que lleva al éxito. - Helen Keller",
    "La vida es demasiado corta para ser pequeña. - Benjamin Disraeli",
    "El conocimiento es poder. - Francis Bacon",
    "La vida es 10% lo que nos sucede y 90% cómo reaccionamos a ello. - Charles R. Swindoll",
    "La creatividad es inteligencia divirtiéndose. - Albert Einstein",
    "El que persevera alcanza. - Proverbio español",
    "La mejor forma de predecir el futuro es crearlo. - Peter Drucker",
    "La disciplina es el puente entre las metas y los logros. - Jim Rohn",
    "El optimismo es la fe que lleva al éxito. - Helen Keller",
    "El éxito consiste en obtener lo que se desea. La felicidad, en disfrutar lo que se obtiene. - Henry Ford",
    "El conocimiento es poder. - Francis Bacon",
    "El éxito no consiste en lo que tienes, sino en quién eres. - Bo Bennett",
];

function generateQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    const randomQuote = quotes[randomIndex];
    document.getElementById("quoteOutput").textContent = randomQuote;
}

document.getElementById("generateQuoteBtn").addEventListener("click", generateQuote);


